// ========== 成语填空 📖 (Idiom Fill) ==========
(function() {
  let state={bet:0,idx:0,score:0,gameOver:false};
  const QS=[{q:'一_当先',o:['马','车','人','刀'],a:0},{q:'_上添花',o:['锦','花','雪','金'],a:0},{q:'画蛇_足',o:['添','加','多','补'],a:0},{q:'_中送炭',o:['雪','雨','风','火'],a:0},{q:'亡羊_牢',o:['补','修','建','围'],a:0},{q:'_目寸光',o:['鼠','蛇','龙','兔'],a:0},{q:'守株_兔',o:['待','等','候','抓'],a:0},{q:'对_弹琴',o:['牛','马','猪','鸡'],a:0},{q:'打草惊_',o:['蛇','龙','虎','兔'],a:0},{q:'叶公好_',o:['龙','凤','虎','马'],a:0}];
  const html=`<div class="game-page" id="page-idiom-fill"><div class="game-top"><button class="back-btn" onclick="Engine.backToHall()">← 大厅</button><h2>📖 成语填空</h2></div><div class="top-bar"><div class="balance-display">💰 <span class="balance-val">0</span></div></div><div class="game-table"><div id="ifProgress" style="font-size:0.8rem;color:#888;"></div><div id="ifQuestion" style="font-size:1.3rem;color:var(--gold);margin:12px 0;"></div><div id="ifOptions" style="display:flex;gap:8px;justify-content:center;flex-wrap:wrap;"></div><div id="ifResult" class="message"></div></div><div class="chips"><div class="chip chip-100" onclick="IF.bet(100)">100</div><div class="chip chip-500" onclick="IF.bet(500)">500</div><div class="chip chip-1000" onclick="IF.bet(1000)">1000</div></div><div class="current-bet">下注：<span id="ifBet">0</span></div><div class="game-controls"><button class="btn" id="ifNextBtn" onclick="IF.next()" style="display:none;">下一题</button><button class="btn" onclick="IF.reset()">重新开始</button></div></div>`;
  document.addEventListener('DOMContentLoaded',()=>{document.getElementById('gamePages').insertAdjacentHTML('beforeend',html);});
  window.IF={
    bet(a){if(state.gameOver)return;if(!Engine.canBet(a))return;state.bet+=a;Engine.state.balance-=a;Engine.save();Engine.updateBalanceUI();document.getElementById('ifBet').textContent=state.bet;Engine.play('click');if(state.bet>0&&state.idx===0)IF.showQ();},
    showQ(){if(state.idx>=QS.length){IF.end();return;}const q=QS[state.idx];document.getElementById('ifProgress').textContent=`第${state.idx+1}/${QS.length}题`;document.getElementById('ifQuestion').textContent=q.q;document.getElementById('ifOptions').innerHTML=q.o.map((o,i)=>`<button class="bet-btn" style="font-size:1.2rem;padding:8px 20px;" onclick="IF.answer(${i})">${o}</button>`).join('');document.getElementById('ifResult').textContent='';document.getElementById('ifNextBtn').style.display='none';},
    answer(i){const q=QS[state.idx];const correct=i===q.a;const res=document.getElementById('ifResult');if(correct){state.score++;res.textContent='✅ 正确！';res.className='message msg-win';Engine.play('win');}else{res.textContent=`❌ 正确答案是：${q.o[q.a]}`;res.className='message msg-lose';Engine.play('lose');}document.querySelectorAll('#page-idiom-fill .bet-btn').forEach((b,idx)=>b.style.borderColor=idx===q.a?'var(--gold)':'#555');document.getElementById('ifNextBtn').style.display='inline-block';},
    next(){state.idx++;IF.showQ();},
    end(){state.gameOver=true;const win=Math.floor(state.bet*(1+state.score*0.3));Engine.addBalance(win);document.getElementById('ifResult').textContent=`🎉 答对${state.score}/${QS.length}题，赢 ${win}！`;document.getElementById('ifResult').className='message msg-win';Engine.play('win');if(state.score>=8)Engine.showQuote('win');},
    reset(){state.bet=0;state.idx=0;state.score=0;state.gameOver=false;document.getElementById('ifBet').textContent='0';document.getElementById('ifQuestion').textContent='';document.getElementById('ifOptions').innerHTML='';document.getElementById('ifResult').textContent='';document.getElementById('ifProgress').textContent='';document.getElementById('ifNextBtn').style.display='none';Engine.updateBalanceUI();}
  };
})();